// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package heartbeat

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson2e157c16DecodeTryOnInternalMiddlewareHeartbeat(in *jlexer.Lexer, out *heartbeatResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "db":
			out.DB = string(in.String())
		case "centrifugo":
			out.Centrifugo = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2e157c16EncodeTryOnInternalMiddlewareHeartbeat(out *jwriter.Writer, in heartbeatResponse) {
	out.RawByte('{')
	first := true
	_ = first
	if in.DB != "" {
		const prefix string = ",\"db\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.DB))
	}
	if in.Centrifugo != "" {
		const prefix string = ",\"centrifugo\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Centrifugo))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v heartbeatResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2e157c16EncodeTryOnInternalMiddlewareHeartbeat(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v heartbeatResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2e157c16EncodeTryOnInternalMiddlewareHeartbeat(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *heartbeatResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2e157c16DecodeTryOnInternalMiddlewareHeartbeat(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *heartbeatResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2e157c16DecodeTryOnInternalMiddlewareHeartbeat(l, v)
}
