// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package delivery

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonCea158a8DecodeTryOnInternalPkgSessionDelivery(in *jlexer.Lexer, out *tokenResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "token":
			out.Token = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCea158a8EncodeTryOnInternalPkgSessionDelivery(out *jwriter.Writer, in tokenResponse) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Token != "" {
		const prefix string = ",\"token\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Token))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v tokenResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCea158a8EncodeTryOnInternalPkgSessionDelivery(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v tokenResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCea158a8EncodeTryOnInternalPkgSessionDelivery(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *tokenResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCea158a8DecodeTryOnInternalPkgSessionDelivery(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *tokenResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCea158a8DecodeTryOnInternalPkgSessionDelivery(l, v)
}
