services:
  backend:
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - 8000:8000
    environment:
      - POSTGRES.PASSWORD
      - POSTGRES.HOST
      - POSTGRES.PORT
      - SESSION.SECRET


  postgres:
    image: postgres:16.2-alpine
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_USER: try-on-admin
      POSTGRES_DB: try-on
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password

secrets:
  postgres_password:
      environment: "POSTGRES.PASSWORD"
