services:
  app:
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
      - centrifugo
      - redis
    environment:
      - POSTGRES.PASSWORD
      - POSTGRES.HOST
      - POSTGRES.PORT
      - SESSION.SECRET
      - RABBIT.PASSWORD
      - RABBIT.HOST
      - STATIC.HTTPAPI.TOKEN
      - STATIC.HTTPAPI.ENDPOINT
      - WEATHER_API_KEY
      - MODELSHEALTH.TOKEN

  centrifugo:
    image: centrifugo/centrifugo:v5
    restart: unless-stopped
    volumes:
      - ./config/centrifugo.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - 8002:8000
    environment:
      - CENTRIFUGO_ADMIN_PASSWORD
      - CENTRIFUGO_ADMIN_SECRET
      - CENTRIFUGO_TOKEN_HMAC_SECRET_KEY
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  postgres:
    image: postgres:16.2-alpine
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_USER: try-on-admin
      POSTGRES_DB: try-on
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
  
  nginx:
    image: nginx:1.25.4-alpine
    restart: unless-stopped
    depends_on:
      - app
      - centrifugo
    ports:
      - 80:80
      - 5432:5432
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
  
  redis:
    image: redis:7.2.4-alpine
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning

secrets:
  postgres_password:
    environment: "POSTGRES.PASSWORD"

networks:
  default:
    external: true
    name: shared-api-network
