-- +migrate Up
-- insert into outfit_purpose(name, eng_name)
-- values ('На работу', 'office clothes'),
--        ('Для прогулок', ''),
--        ('Для активного отдыха', ''),
--        ('В спортзал', ''),
--        ('Для пляжа', ''),
--        ('В театр', '');
