// Code generated by "stringer -type=Season"; DO NOT EDIT.

package seasons

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Winter-0]
	_ = x[Spring-1]
	_ = x[Summer-2]
	_ = x[Autumn-3]
}

const _Season_name = "WinterSpringSummerAutumn"

var _Season_index = [...]uint8{0, 6, 12, 18, 24}

func (i Season) String() string {
	if i >= Season(len(_Season_index)-1) {
		return "Season(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Season_name[_Season_index[i]:_Season_index[i+1]]
}
