// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  try_on

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( ratingRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ratingRequest ) UnmarshalJSON([]byte) error { return nil }
func ( ratingRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ratingRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ratingRequest *ratingRequest

func ( tryOnOutfitRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* tryOnOutfitRequest ) UnmarshalJSON([]byte) error { return nil }
func ( tryOnOutfitRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* tryOnOutfitRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_tryOnOutfitRequest *tryOnOutfitRequest

func ( tryOnRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* tryOnRequest ) UnmarshalJSON([]byte) error { return nil }
func ( tryOnRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* tryOnRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_tryOnRequest *tryOnRequest
