on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: golang

    steps:
      - uses: actions/checkout@v4

      - name: Build
        env:
          GOFLAGS: "-buildvcs=false"
        run: make build_alpine

      - name: Push build data
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.BACKEND_IP_ADDR }}
          username: ubuntu
          overwrite: true
          key: ${{ secrets.BACKEND_SSH_KEY }}
          source: "build,config,scripts,static,Dockerfile,docker-compose.yml"
          target: ~/app/backend

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.BACKEND_IP_ADDR }}
          username: ubuntu
          key: ${{ secrets.BACKEND_SSH_KEY }}
          script: |
            cd ~/app/backend
            chmod 700 ./scripts/deploy.sh
            ./scripts/deploy.sh
